import type { Metadata } from "next";
import { Jost} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";

const jost = Jost({
  subsets: ['latin'],
  weight: ['400', '700'], 
  variable: '--font-jost', 
  display: 'swap',
});

export const metadata: Metadata = {
  title: "SafeGuard AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jost.className} antialiased`}
      >
        <ThemeProvider>
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
